Sangmin627/AlgoStudy2023

상민/백준/구현/10994/README.md
상민/백준/구현/10994/main.cpp
상민/백준/구현/14916/README.md
상민/백준/구현/14916/main.cpp
상민/백준/구현/20436/README.md
상민/백준/구현/20436/main.cpp

백준 10994, 14916, 20436 풀이

---

상진/Baekjoon/Greedy/BOJ11399.py
상진/Baekjoon/Greedy/BOJ1343.py
상진/Baekjoon/Greedy/BOJ14916.py
상진/Baekjoon/Greedy/BOJ1758.py
상진/Baekjoon/Greedy/BOJ2217.py

- while 문을 통해 n값을 줄여감
- n이 5로 나누어떨어진다면, n에서 5를 뺌
- 그게 아니라면 n에서 2를 뺌
```python
answer = 0
while n > 1:
if n % 5 != 0:
n -= 2
answer += 1
else:
n -= 5
answer += 1
```
- 조건문 후, 남은 값이 1이라면 나누어떨어지지 않는 값이므로 -1을 출력함
```python
if n == 0:
print(answer)
else:
print(-1)
```
---
```python
flag = True # X 개수가 홀수개라면 False
countX = 0 
answer = ""
```
- 처음 문자열을 입력받을 때, 문자열 마지막에 ‘.’을 추가함
```python
board  = list(input())
board.append(".")
```
- 입력받은 문자열(board)를 반복문 돌며,
- board[i] 가 ‘X’라면, countX의 수를 증가시킴
```python
for i in range(len(board)):
if board[i] == "X":
countX += 1
```
- board[i] 가 ‘.’이라면, countX를 통해 폴리오미노로 정답을 채움
- countX가 홀수라면, flag를 False로 바꾸고 반복문을 끝냄
```python
if countX % 2 != 0:
flag = False
break
```
- countX가 4이상이라면, 4로 나눈 몫 * 4 만큼 AAAA로 치환하고, 나머지를 BB로 치환함
```python
if countX >= 4:
answer += …
```

[상진] 백준 #14916, #1343, #2217, #1758, #11399

---

상진/Baekjoon/Graph-Traversal/BOJ13549.py
상진/Baekjoon/Graph-Traversal/BOJ16234.py
상진/Baekjoon/Graph-Traversal/BOJ17836.py
상진/Baekjoon/Graph-Traversal/BOJ7569.py
상진/Baekjoon/Graph-Traversal/BOJ7576.py

```python
from collections import deque
import sys
dx = [-1, 0, 1, 0]
dy = [0, 1, 0, -1]
m, n = map(int, input().split())
g = [] # 토마토 저장 리스트
q = deque() # BFS 사용을 위한 큐
```
- 입력 값에 따라 `g`를 초기화하며, 토마토가 존재하는 위치의 인덱스를 `q`에 저장한다.
```python
for i in range(n):
g.append(list(map(int, input().split())))
for j in range(m):
if g[i][j] == 1:
q.append((i, j))
```
- BFS를 이용하여 그래프 탐색을 진행한다. 단, `g[ny][nx] == 0` 조건을 추가하고, 조건을 만족하면 `이전 값 + 1` 을 한다.
```python
while q:
y, x = q.popleft()
for i in range(4):
ny = y + dy[i]
nx = x + dx[i]
if 0 <= ny < n and 0 <= nx < m and g[ny][nx] == 0:
g[ny][nx] = g[y][x] + 1
q.append((ny, nx))
```
- 그래프내의, 0이 존재하면 모두 익지 못하는 경우이므로, -1을 출력하고, 그게 아니라면 `g에서 가장 큰 값 - 1`을 정답으로 출력한다.
- 시작 값이 1이므로 !
```python
for i in range(n):
for j in range(m):
if …
```

[상진, 7주차 - 그래프 탐색] 백준 #7576, #7569, #16234, #13549, #17836

---

상진/Baekjoon/Dynamic-Programming/BOJ12865.py
상진/Baekjoon/Dynamic-Programming/BOJ2225.py
상진/Baekjoon/Dynamic-Programming/BOJ5557.py
상진/Baekjoon/Dynamic-Programming/BOJ9084.py
상진/Baekjoon/Dynamic-Programming/BOJ9251.py

```python
N = int(input()) # 동전의 개수
coins = [0] + list(map(int, input().split())) # 동전의 화폐단위
money = int(input()) # 입력받은 금액
```
- 화폐 단위를 기준으로, 해당 화폐단위 ~ 입력받은 금액까지 반복문을 돌리며 `memo`를 할당한다.
```python
memo = [0] * (money+1) # memo[i] : i원을 만들 수 있는 경우의 수
memo[0] = 1
for i in range(1, N+1):
for j in range(coins[i], money+1):
memo[j] += memo[j-coins[i]]
print(memo[-1])
```
- `memo[i]` = 주어진 동전을 통해 i원을 만들 수 있는 경우의 수
- `memo[0] = 1`
- 초기 값 설정을 위해 memo[0]은 1로 초기화한다.
<ul>
<li><code>memo[j] += memo[j-coins[i]]</code>
<ul>
<li>
<p>이전의 동전들을 가지고 만든 금액에 현재의 동전을 추가하여 계속해서 누적한다.</p>
</li>
<li>
<p>e.g. coins = [1,2,3], money = 7</p>
  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
2 | 1 | 1 | 2 | 2 | 3 | 3 | 4 | 4
3 | 1 | 1 | 2 | 3 | 4 | 4 | 7 | 8 …

[상진, 8주차 - DP] #9084, #12865, #9251, #2225, #5557

---

상진/Baekjoon/Dynamic-Programming/BOJ14567.py
상진/Baekjoon/Dynamic-Programming/BOJ14728.py
상진/Baekjoon/Dynamic-Programming/BOJ17485.py
상진/Baekjoon/Dynamic-Programming/BOJ2624.py
상진/Baekjoon/Dynamic-Programming/BOJ3067.py

```python
import sys
MONEY = int(input())
coins = [[0,0]] # 인덱스를 1로 맞추기 위함
memo = [[0] * (MONEY+1) for _ in range(N+1)]
```
- [금액, 개수]를 갖는 coins를 초기화한다.
```python
for i in range(N):
p,n = map(int, input().split())
coins.append([p,n])
```
- **DP 전체 코드**
```python
for i in range(N+1):
memo[i][0] = 1
for i in range(1,N+1):
val, cnt = coins[i]
for j in range(1,MONEY+1):
memo[i][j] = memo[i-1][j]
for c in range(1, cnt+1):
for j in range(c*val, MONEY+1):
memo[i][j] += memo[i-1][j - val * c]
print(memo[-1][-1])
```
- 현재 동전을 사용하지 않는 경우를 계산하기 위해 초기화 이전의 경우의 수로 초기화한다.
```python
for j in range(1,MONEY+1):
memo[i][j] = memo[i-1][j]
```
- 가지고 있는 개수를 기준으로, 값들을 계산한다. (말로는 설명하기 힘드니까 그림을 통해 스터디원들에게 보여주기!)
- `memo[i][j]` : `i`원 동전(c개)을 이용하여 `j`원을 만들 수 있는 경우의 수
- …

[상진, 9주차 - DP] 백준 #2624, #14567, #17485, #3067, #14728

---

상진/Baekjoon/Backtracking/BOJ10974.py
상진/Baekjoon/Backtracking/BOJ10974_permutation.py
상진/Baekjoon/Backtracking/BOJ16922.py
상진/Baekjoon/Backtracking/BOJ16922_중복순열.py
상진/Baekjoon/Backtracking/BOJ18429.py
상진/Baekjoon/Two-Pointer/BOJ21921.py
상진/Baekjoon/Two-Pointer/BOJ3273.py

```python
import sys
ans = [] # 순열 저장 리스트
```
- 재귀문(dfs)을 이용하여 탐색한다.
- `len(ans) == N`: 순열의 길이가 N이라면 재귀문을 탈출한다.
- 재귀문을 탈출한 후, `ans.pop()`을 통해 계속해서 순열을 찾는다.
```python
def dfs():
if len(ans) == N:
print(*ans)
return
for i in range(1, N+1):
if i not in ans:
ans.append(i)
dfs()
ans.pop()
dfs()
```
- 다음과 같이 print문을 이용하여 이해를 더 편하게 할 수 있다 !
```python
def dfs():
if len(ans) == N:
#print(*ans)
print("finish:", ans)
return
for i in range(1, N+1):
if i not in ans:
print(i, "not in", ans)
ans.append(i)
dfs()
ans.pop()
print("end:", i, ans)
```
```python
import sys
from itertools import permutations
N = int(input().rstrip())
perm = list(permutations(map(str, range(1,N+1)), N))
for p in perm:
print(" ".join(p))
```
- 백트래킹 / 순열 두 …

[상진, 11주차 - 백트래킹, 투포인터] #10974, #16922, #18429, #21921, #3273

---

창재/백준/백트레킹/week11/10974/10974.py
창재/백준/백트레킹/week11/16922/16922.py
창재/백준/백트레킹/week11/18429/18429.py
창재/백준/백트레킹/week11/21921/21921.py
창재/백준/백트레킹/week11/3273/3273.py

[창재] week11

---

상진/Baekjoon/Binary-Search/BOJ11663.py
상진/Baekjoon/Binary-Search/BOJ19637_with_recursion.py
상진/Baekjoon/Binary-Search/BOJ19637_without_recursion.py
상진/Baekjoon/Binary-Search/BOJ2512.py
상진/Baekjoon/Shortest-Path/BOJ1058.py
상진/Baekjoon/Shortest-Path/BOJ1058_brute-force.py
상진/Baekjoon/Shortest-Path/BOJ18352.py
상진/Baekjoon/Shortest-Path/BOJ18352_BFS.py

```python
import sys
nums = sorted(list(map(int, input().split()))) # 이분 탐색을 위한 정렬!
M = int(input())
```
- sum(nums) <= M 이라면, 가장 큰 수를 정답으로 출력한다.
- 그게 아니라면 `binary` 함수를 호출한다.
```python
if sum(nums) <= M:
print(nums[-1])
exit()
binary(0, nums[-1])
```
- `binary(left, right)` : 이분 탐색 함수
- `mid` : 상한 값
- `left > right`의 경우, `right`를 출력하고 호출을 끝낸다.
- `total` : `mid`(상한 값)를 이용한 `nums`의 총 합
- 만약 상한 값보다 작다면 기존 값을 더하고, 크다면 상한 값을 더해서 계산한다.
- `total <= M` : 현재 계산한 총 합이 `M`보다 작다면, `left`를 `mid+1`로 재귀를 진행한다. (값을 높여야하므로!)
- `total > M` : 현재 계산한 총 합이 `M`보다 크다면, `right`를 `mid-1`로 재귀를 진행한다. (값을 낮춰야하므로!)
```python
def binary(left, right):
if left > right:
print(right)
return
total = 0
mid = (left + right) // 2
for num in nums:
if num <= mid:
total += num
else: …
```

[상진, 12주차 - 이분탐색, 최단경로] 백준 #2512, #19637, #11663, #18352, #1058

---

창재/백준/이분탐색/week12/1058/1058.py
창재/백준/이분탐색/week12/11663/11663.py
창재/백준/이분탐색/week12/18352/18352.py
창재/백준/이분탐색/week12/19637/19637.py
창재/백준/이분탐색/week12/2512/2512.py

[창재] week12

---

상진/Baekjoon/Practice/BOJ12026.py
상진/Baekjoon/Practice/BOJ17251.py
상진/Baekjoon/Practice/BOJ18404.py
상진/Baekjoon/Practice/BOJ2529.py
상진/Baekjoon/Practice/BOJ9518.py

```python
import sys
arr = list(map(str, input().split()))
idx = 0 # arr의 idx를 추적하기 위함
ans = [] # 결과 값
tmp = [] # 백트래킹 도중의 값
```
- `if len(tmp) == N+1` : 재귀 탈출 조건
- 만약 부등호가 < 라면, `tmp[-1]` 값과 현재 값을 비교한 후, 큰 값을 넣는다.
- 단 `tmp`의 길이가 `1 이상`일 때만 ! (길이가 `0`인 경우, `tmp[-1]` 에서 `IndexError` 발생)
- `idx` : 부등호를 추적하는 인덱스로, 백트래킹을 진행하며 탈출조건이라면, `idx -= 1` 을 통해 다시 탐색하도록 한다.
```python
def dfs():
global idx
if len(tmp) == 0:
for i in range(10):
tmp.append(str(i))
dfs()
tmp.pop()
if len(tmp) == N+1:
ans.append("".join(tmp))
return
for i in range(10):
if str(i) not in tmp:
if arr[idx] == '<' and len(tmp) >= 1:
if i > int(tmp[-1]):
tmp.append(str(i))
idx += 1
dfs()
tmp.pop()
idx -= 1
elif arr[idx] == '>' and len(tmp) >= 1:
if i < int(tmp[-1]):
tmp.append(str(i)) …
```

[상진, 13주차] 백준 #2529, #9518, #17251, #18404, #12026

---

창재/백준/random/12026.py
창재/백준/random/17251.py
창재/백준/random/18404.py
창재/백준/random/2529.py
창재/백준/random/9518.py

Week12 랜덤 문제

---

상진/Baekjoon/Practice/BOJ1527.py
상진/Baekjoon/Practice/BOJ15658.py
상진/Baekjoon/Practice/BOJ16973.py
상진/Baekjoon/Practice/BOJ1986.py
상진/Baekjoon/Practice/BOJ2230.py

```python
from collections import deque
import sys
dy = [0,1,0,-1]
dx = [1,0,-1,0]
N,M = map(int, input().split())
g = [] # 입력 받은 배열 리스트
wall = [] # 벽을 저장하는 리스트
movable = [[0] * M for _ in range(N)] # 왼쪽 위 시작점이 움직일 수 있는 2차원 리스트
visited = [[-1] * M for _ in range(N)] # 이동 횟수 저장
H,W,SR,SC,FR,FC = map(int, input().split())
```
- 배열을 입력받으면서, 벽의 위치를 `wall` 에 저장한다.
```python
for i in range(N):
g.append(list(map(int, input().split())))
for j in range(M):
if g[i][j] == 1:
wall.append((i,j))
```
- `wall`의 `(y,x)` 인덱스를 끝점으로, 왼쪽위 시작점이 움직일 수 있는 `movable` 리스트를 초기화한다.
- `if ey + 1 >= H` : 만약 끝 점이 `H`보다 크거나 같다면, `sy = ey + 1 - H`로 초기화한다.
- 그게 아니라면, `sy = 0`으로 초기화한다.
- `sx`값도 위와 같이 초기화한다.
```python
def init_movable(ey,ex):
if ey + 1 >= H:
sy = ey + 1 - H
else:
sy = 0
if ex + 1 …
```

[상진, 14주차] 백준 #16973, #1986, #1527, #2230, #15658

---

상진/Programmers/Level2/[3차] n진수 게임.py
상진/Programmers/Level2/[3차] 압축.py
상진/Programmers/Level2/[3차] 파일명 정렬.py
상진/Programmers/Level2/오픈채팅방.py
상진/Programmers/Level2/주차 요금 계산.py

```python
dic = {} 
dic_idx = 1 # 딕셔너리 인덱스 추적용
```
- (알파벳 - 숫자) 쌍을 갖는 딕셔너리를 초기화한다.
```python
for i in range(65, 91):
dic[chr(i)] = dic_idx
dic_idx += 1
```
- 투포인터를 통해 문제를 해결한다.
- `n` : `msg[s:e+1]`, 사전에 등록된 최대 길이 문자 + 다음 문자
- 만약 n이 딕셔너리에 저장되어 있지 않다면,
- 딕셔너리에 해당 단어를 등록한 후, `dic[msg[s:e]]`를 `answer`에 추가한다.
e.g. KA가 처음 나오는 경우, K만 답으로 출력해야함
- `s`를 현재의 `e`로, `e`를 `+1` 한 값으로 초기화한다.
- 만약 n이 딕셔너리에 저장된 상태라면, `e`를 +1 한 후, 다시 반복한다.
```python
s, e = 0, 1
while e < len(msg):
n = msg[s:e + 1]
if n not in dic.keys():
dic[n] = dic_idx
dic_idx += 1
answer.append(dic[msg[s:e]])
s = e
e += 1
else:
e += 1
answer.append(dic[msg[s:e]])
return answer
```
- 인덱스 관리가 조금은 복잡했던 문제 !
---
```python
answer = ''
tmp = ' 0' # 인덱스를 맞추기 위해 " " 추가
idx = 0 
dic = dict() # (수 - 진수) 쌍의 딕셔너리
```
- 딕셔너리를 (0-15, ‘0’-’F’) 쌍을 갖도록 …

[상진, 17주차] 프로그래머스 #[3차] 압축, #[3차] n진수 게임, #주차 요금 계산, #오픈채팅방, #[3차] 파일명 정렬

---

창재/프로그래머스/3차/[2018 KAKAO BLIND RECRUITMENT] [1차] 프렌즈4블록.py
창재/프로그래머스/3차/[2021 KAKAO BLIND RECRUITMENT] 메뉴 리뉴얼.py
창재/프로그래머스/3차/[2022 KAKAO TECH INTERNSHIP] 두 큐 합 같게 만들기.py

[1차] 프렌즈4블록, 두 큐 합 같게 만들기, 메뉴 리뉴얼

---

상진/Programmers/Level2/[1차] 프렌즈4블록.py
상진/Programmers/Level2/[3차] 방금그곡.py
상진/Programmers/Level2/괄호 변환.py
상진/Programmers/Level2/두 큐 합 같게 만들기.py
상진/Programmers/Level2/메뉴 리뉴얼.py

- `check` : 2X2 블록의 위치를 하나의 리스트로 반환해주는 함수
- 자신을 기준으로 2X2 위치에 자신과 같은 값이 존재한다면, `tmp`에 추가한다.
- `tmp`의 길이가 4 라면, `blocks`에 `extend`로 합친다.
- `extend`로 합친 이유는, 2X2가 겹치는 부분을 `set`을 이용하여 제거하기 위함 !
```python
def check(m,n,b):
blocks = []
for i in range(m-1):
for j in range(n-1):
if b[i][j] == 0:
continue
tmp = []
tmp.append((i,j))
now = b[i][j]
if b[i+1][j] == now:
tmp.append((i+1, j))
if b[i][j+1] == now:
tmp.append((i,j+1))
if b[i+1][j+1] == now:
tmp.append((i+1, j+1))        
if len(tmp) == 4:
blocks.extend(tmp)
return list(set(blocks))
```
- `change` : `check`에서 반환된 `blocks`에 해당하는 값들을 0으로 초기화하는 함수
```python
def change(blocks, b):
for y,x in blocks:
b[y][x] = 0
```
- `down` : `change`로 인해 0이 된 값 위에 존재하는 블럭들을 밑으로 내려주는 함수
- 만약 `b[i][j]`값이 존재하고, `b[i+1][j]` 가 0인 경우, 이 둘의 자리를 바꾼다.
- 자리를 바꾼 적이 있다면 …

[상진, 18주차] 프로그래머스 #[1차] 프렌즈4블록, #두 큐 합 같게 만들기, #메뉴 리뉴얼, #괄호 변환, #[3차] 방금그곡

---

상민/프로그래머스/2018_카카오_방금그곡.cpp
상민/프로그래머스/2018_카카오_프렌즈4블록.cpp
상민/프로그래머스/2020_카카오_괄호변환.cpp
상민/프로그래머스/2021_카카오_메뉴리뉴얼.cpp

[상민, 18주차] 프로그래머스 # [1차] 프렌즈4블록,  # 메뉴 리뉴얼, #괄호 변환, #방금 그곡

---

창재/백준/유니온파인드/week19/10775.py
창재/백준/유니온파인드/week19/1717.py
창재/백준/유니온파인드/week19/1976.py
창재/백준/유니온파인드/week19/20040.py
창재/백준/유니온파인드/week19/4195.py

[창재, 19주차 - 유니온파인드] 백준 #20040, #1976, #1717, #4195, #10775

---

상진/Baekjoon/Tree/BOJ1068.py
상진/Baekjoon/Tree/BOJ14675.py
상진/Baekjoon/Tree/BOJ17073.py
상진/Baekjoon/Tree/BOJ1991.py
상진/Baekjoon/Tree/BOJ9934.py

```python
import sys
tree = dict() # 자신노드 = [왼쪽자식노드, 오른쪽자식노드] 모양으로 저장
```
- `tree`를 초기화한다.
```python
for i in range(N):
val, left, right = map(str, input().split())
tree[val] = [left, right]
```
- 각각의 순회를 진행한다.
- `전위순회(preorder)` : 루트 → 왼쪽 → 오른쪽
```python
def preorder(node):
if node != ".":
print(node, end='')
preorder(tree[node][0])
preorder(tree[node][1])
```
- `중위순회(inorder)` : 왼쪽 → 루트 → 오른쪽
```python
def inorder(node):
if node != ".":
inorder(tree[node][0])
print(node,end='')
inorder(tree[node][1])
```
- `후위순회(postorder)` : 왼쪽 → 오른쪽 → 루트
```python
def postorder(node):
if node != ".":
postorder(tree[node][0])
postorder(tree[node][1])
print(node,end='')
```
- 문제 조건에 따라 `순위 - 중위 - 후위` 순으로 함수를 호출한다.
```python
preorder('A')
print()
inorder('A') …
```

[상진, 20주차 - 트리] 백준 #1991, #1068, #9934, #14675, #17073

---

창재/백준/DFS&BFS/week7/13549/13549.py
창재/백준/DFS&BFS/week7/16234/16234.py
창재/백준/DP/week8/9251/9251.py
창재/백준/DP/week9/17485/17485.py
창재/백준/random/week14/15658.py
창재/백준/random/week15/5639.py
창재/백준/트리/week20/1068.py
창재/백준/트리/week20/14675.py
창재/백준/트리/week20/17073.py
창재/백준/트리/week20/1991.py
창재/백준/트리/week20/9934.py

[창재 20주차 - 트리] 백준 #1991, #1068, #9934, #14675, #17073

---

상민/백준/백트래킹/1062.cpp
상민/백준/백트래킹/14712.cpp
상민/백준/백트래킹/16938.cpp
상민/백준/백트래킹/3980.cpp

백준 1062, 3980, 14712, 16938 풀이

---

상진/Baekjoon/Greedy/BOJ13975.py
상진/Baekjoon/Greedy/BOJ1715.py
상진/Baekjoon/Greedy/BOJ21758.py
상진/Baekjoon/Greedy/BOJ2812.py

```python
import sys
arr = list(map(int, input().split()))
```
- 벌과 꿀이 가능한 경우는 3가지 !
- `ans1` : 벌 하나가 왼쪽 끝, 꿀이 오른쪽 끝에 있는 경우
- `prefix_sum` 초기화
- 나머지 벌을 `1~N-2`까지 위치를 변경하면서 최대 누적합 구한다.
- `ans2` : 벌 하나가 오른쪽 끝, 꿀이 왼쪽 끝에 있는 경우
- `suffix_sum` 초기화
- 나머지 벌을 `N-2~1`까지 위치를 변경하면서 최대 누적합 구한다.
- `ans3` : 벌이 양쪽 끝에 있는 경우
- `arr[1]~arr[N-2]` 중, 가장 높은 값에 꿀을 위치시킨다.
- **누적합 구하는 방법 (suffix)**
- `ans3 = sum(arr[1:N-1]) + max(arr[1:N-1]`
- 벌이 양쪽에 있는 경우, `arr[1]~arr[N-1]`까지 다 더한 후, 꿀이 있는 위치를 한번 더 더하므로 최대값을 찾아 더해준다.
```python
prefix_sum = [0] * N
suffix_sum = [0] * N
ans1, ans2, ans3 = 0,0,0
prefix_sum[0] = 0
for i in range(1,N):
prefix_sum[i] = prefix_sum[i-1] + arr[i]
for i in range(1,N-1):
ans1 = max(prefix_sum[-1] - prefix_sum[i] + prefix_sum[-1] - arr[i], ans1) …
```

[상진, 22주차 - 그리디] 백준 #21758, #13975, #1715, #2812

---

상진/Baekjoon/Dynamic-Programming/BOJ18427.py
상진/Baekjoon/Dynamic-Programming/BOJ1915.py
상진/Baekjoon/Dynamic-Programming/BOJ2073.py
상진/Baekjoon/Dynamic-Programming/BOJ2631.py
상진/Baekjoon/Dynamic-Programming/BOJ2758.py

```python
import sys
N,M,H = map(int, input().split())
arr = [sorted(list(map(int, input().split()))) for _ in range(N)]
memo = [[0] * (H+1) for _ in range(N+1)]
```
- `memo[i][j]` : `i`번째 사람이 블록을 쌓아 높이가 `j` 인 탑을 만들 수 있는 경우의 수
- 블록을 사용하지 않는 경우(`memo[i][0]`)에 대해 초기화를 한다.
- `memo[i][j] = memo[i-1][j]` : 이전 사람이 쌓아올렸던 경우의 수를 그대로 자신의 경우의 수에 추가한다.
- `for k in arr[i-1]:` 자신이 갖고 있는 높이가 `k`인 블록들을 가지고,
- `if j >= k` : 만약 만들고자하는 `j`(탑의 높이)가 `k` (자신이 가진 블록의 높이) 이상이라면,
- `memo[i][j] += memo[i-1][j-k]` : 이전 사람들이 `j-k` 탑의 높이를 쌓아올린 경우의 수 + 자신의 블록을 쌓는 경우의 수를 더한다.
```python
for i in range(N+1):
memo[i][0] = 1
for i in range(1,N+1):
for j in range(1,H+1):
memo[i][j] = memo[i-1][j]
for k in arr[i-1]:
if j >= k:
memo[i][j] += memo[i-1][j-k]
print(memo[-1][-1] % 10007)
```
- 3중 반복문을 …

[상진, 23주차 - DP] 백준 #18427, #1915, #2631, #2758, #2073

---

상진/Baekjoon/Random-Defence/BOJ10835.py
상진/Baekjoon/Random-Defence/BOJ12764.py
상진/Baekjoon/Random-Defence/BOJ15683.py
상진/Baekjoon/Random-Defence/BOJ3671.py
상진/Baekjoon/Random-Defence/BOJ5502.py

```python
import sys
S = list(input().rstrip())
memo = [[0] * (N+1) for _ in range(N+1)]
```
- `LCS(최장 공통 부분 수열)` 문제
- `memo[i][j]` : 정방향 `S[:i]`와 역방향 `R[:j]`에 대한 공통 부분 수열의 길이
- 최장 공통 부분 수열을 구한 후, 전체 길이에서 해당 길이를 빼준 값을 출력한다.
```python
for i in range(1, N+1):
start = S[i-1]
for j in range(1, N+1):
rev = S[N-j]
if start == rev:
memo[i][j] = memo[i-1][j-1] + 1
else:
memo[i][j] = max(memo[i-1][j], memo[i][j-1])
print(N-memo[-1][-1])
```
- 예전에 분명히 비슷한 문제를 풀었는데 문제 풀이 당시에 도저히 기억이 안나 구글 찬스를 쓴 문제🥲
- `8주차 DP - #9251`
---
```python
import sys, copy
dy = [0,1,0,-1]
dx= [1,0,-1,0]
N,M = map(int, input().split())
g = []
cctvs = [] # [CCTV 종류, y, x]
ans = 65
```
- cctv 종류와, 해당 위치를 `cctvs`에 저장한다.
```python
for i in range(N): …
```

[상진 - 25주차, 랜덤문제] 백준 #5502, #15683, #12764, #10835, #3671

---

창재/프로그래머스/week26/[프로그래머스] [2019 KAKAO BLIND RECRUITMENT] 후보키.py
창재/프로그래머스/week26/[프로그래머스] [2020 KAKAO BLIND RECRUITMENT] 문자열 압축.py
창재/프로그래머스/week26/[프로그래머스] [2020 카카오 인턴십] 수식 최대화.py
창재/프로그래머스/week26/[프로그래머스] [2021 카카오 채용연계형 인턴십] 거리두기 확인하기.py
창재/프로그래머스/week26/[프로그래머스] [2022 KAKAO BLIND RECRUITMENT] 양궁대회.py

[창재 - 26주차] 프로그래머스 #수식 최대화, #거리두기 확인하기, #문자열 압축, #후보키, #양궁대회

---

상진/Programmers/Level3/네트워크.py
상진/Programmers/Level3/야근 지수.py
상진/Programmers/Level3/이중우선순위큐.py
상진/Programmers/Level3/정수 삼각형.py
상진/Programmers/Level3/최고의 집합.py

- `memo[i][j]` = `(i,j)`를 지날때까지의 최대 점수
- `memo[0][0]`을 처음 값으로 초기화한다.
- `j == 0` 일때, `j == i`일때, 그리고 나머지의 경우에 대해 `memo`를 초기화한다.
- `j == 0` : `(i,0)`의 경우(첫번째 열), `(i-1,0)`에서 내려오는 경우만 존재
- `j == i` : `(i,i)`의 경우(마지막 열), `(i-1,i-1)`에서 내려오는 경우만 존재
- 그 이외 : `(i,j)`의 경우, `(i-1,j-1)`, `(i-1,j)`에서 내려오는 두 가지 경우 존재 → 최대값을 구한 후, 현재 값을 더한다.
```python
def solution(triangle):
memo = [[0] * len(triangle[-1]) for _ in range(len(triangle))]
memo[0][0] = triangle[0][0]
for i in range(1, len(triangle)):
for j in range(i+1):
if j == 0:
memo[i][j] = memo[i-1][j] + triangle[i][j]
elif j == i:
memo[i][j] = memo[i-1][j-1] + triangle[i][j]
else:
memo[i][j] = max(memo[i-1][j-1], memo[i-1][j]) + triangle[i][j]
return max(memo[-1])
```
- 전형적인 2차원 DP 문제 !
---
```python
import heapq
```
- `minq` : 최소힙, `maxq` : 최대힙
- …

[상진 - 27주차] 프로그래머스 #정수삼각형, #이중우선순위큐, #네트워크, #최고의 집합, #야근 지수

---

상진/Programmers/Level3/기지국 설치.py
상진/Programmers/Level3/단속카메라.py
상진/Programmers/Level3/단어 변환.py
상진/Programmers/Level3/등굣길.py
상진/Programmers/Level3/숫자 게임.py

- `def check(now, next)` : 현재 단어와 다음 단어를 비교하며 한글자만 차이나는지 확인하는 함수
- 한 글자만 차이나면 `True` 반환, 그게 아니라면 `False` 반환
```python
def check(now, next):
cnt = len(now)
for i in range(len(now)):
if now[i] == next[i]:
cnt -= 1
if cnt != 1:
return False
return True
```
- `def back(cnt, word)` : 백트래킹을 진행하면서 최소 개수를 갱신하는 함수
**종료조건**
- 만약 현재 단어(`now`)가 `target`가 같다면, `answer`를 최소값(`cnt`)으로 갱신하고, `flag`를 `True`로 변경한다.
**재귀조건**
- 만약 방문하지 않은 단어인 경우,
- `check()` 메서드를 통해 한 글자만 차이나는 경우에,
- `visited[i]`를 1로, `cnt`를 1 증가시킨 후, 다음 단어에 대해 백트래킹을 진행한다.
```python
def back(cnt, word):
global answer, flag
if word == target:
answer = min(answer, cnt)
flag = True
return
for i in range(size):
if not visited[i]:
if check(word, words[i]):
visited[i] = 1
cnt += 1
back(cnt, words[i])
cnt -= 1
visited[i] = 0
```
- `메인함수 (전체 함수)`
- …

[상진 - 28주차] 프로그래머스 #단어 변환, #등굣길, #숫자 게임, #단속카메라, #기지국 설치

---

상진/Programmers/Level3/베스트 앨범.py
상진/Programmers/Level3/보석 쇼핑.py
상진/Programmers/Level3/불량 사용자.py
상진/Programmers/Level3/스티커 모으기(2).py
상진/Programmers/Level3/징검다리 건너기.py

- 두개의 딕셔너리로 문제를 해결한다.
- `genres_dic` :  `(장르 - 총 재생된 횟수)`
- `plays_dic` : `(장르 - (재생된 횟수, 인덱스))`
- `genres_dic` 에 대해 총 재생된 횟수를 기준으로 내림차순으로 정렬한 이후, 해당 `key`값에 해당하는 `plays_dic`에 대해 많이 재생한 순, 그리고 고유번호가 낮은 순으로 정렬한다
```python
def solution(genres, plays):
answer = []
genres_dic = dict()
plays_dic = dict()
size = len(genres)
for i in range(size):
genre = genres[i]
play = plays[i]
if genre not in plays_dic.keys():
plays_dic[genre] = [(play, i)]
else:
plays_dic[genre].append((play, i))
if genres[i] not in genres_dic.keys():
genres_dic[genre] = plays[i]
else:
genres_dic[genre] += plays[i]
sorted_genres = sorted(genres_dic.items(), key=lambda x: -x[1])
for key, val in sorted_genres:
cnt = 0
sorted_plays = sorted(plays_dic[key], key=lambda x: (-x[0], x[1]))
for streaming_cnt, idx in sorted_plays:
if …
```

[상진 - 29주차] 프로그래머스 #베스트 앨범, #스티커 모으기(2), #불량 사용자, #보석 쇼핑, #징검다리 건너기

---

상진/Programmers/Level3/가장 먼 노드.py
상진/Programmers/Level3/경주로 건설.py
상진/Programmers/Level3/디스크 컨트롤러.py
상진/Programmers/Level3/섬 연결하기.py
상진/Programmers/Level3/여행경로.py

```python
from collections import deque
```
- `edge`에 담긴 정보를 `g`에 할당시킨다.
- `g[i]` : `i`번째 노드와 연결된 다른 노트 리스트
- BFS를 통해 노드간의 최단 거리를 계산한 후, 1과의 최장거리에 대한 `count`를 반환한다.
```python
def solution(n, edge):
answer = 0
g = [[] for _ in range(n+1)]
for s,e in edge:
g[s].append(e)
g[e].append(s)
visited = [-1] * (n+1)
q = deque()
q.append(1)
visited[1] = 0
while q:
now = q.popleft()
for i in g[now]:
if visited[i] == -1: 
visited[i] = visited[now] + 1
q.append(i)
max_val = max(visited)
answer = visited.count(max_val)
return answer
```
- 그냥 간단한 BFS 문제 !
---
**MST (Minimum Spanning Tree : 최소 신장 트리)**
**Spanning Tree (신장 트리)**
- 그래프 내의 모든 노드가 싸이클 없이 연결된 트리
- n개의 노드가 존재하면 n-1개의 간선으로 이루어진다.
**Minimum Spanning Tree (신장 트리)**
- 신장 트리 중, 사용된 간선들의 가중치 합이 최소인 신장 트리
- 즉, 네트워크에 있는 모든 정점들을 가장 적은 수의 간선과 비용으로 연결하는 …

[상진 - 30주차] 프로그래머스 #가장 먼 노드, #섬 연결하기, #여행경로, #디스크 컨트롤러, #경주로 건설

---

창재/백준/DP/15486.py
창재/백준/DP/LIS(최장 증가 수열)/11053.py
창재/백준/DP/LIS(최장 증가 수열)/11055.py
창재/백준/DP/LIS(최장 증가 수열)/1965.py
창재/백준/DP/혼자/11727.py
창재/백준/DP/혼자/1912.py
창재/백준/DP/혼자/2407.py
창재/프로그래머스/week29/[프로그래머스] 징검다리 건너기.py
창재/프로그래머스/week30/[프로그래머스] 가장 먼 노드.py
창재/프로그래머스/week30/[프로그래머스] 디스크 컨트롤러.py
창재/프로그래머스/week30/[프로그래머스] 여행경로.py

[창재] 개인 연습 풀이
